CREATE TABLE "voluntarios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(80) NOT NULL,
  "sobrenome" varchar(50) NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "senha" varchar(255) NOT NULL,
  "telefone" varchar(20) UNIQUE,
  "nascimento" date,
  "biografia" varchar(500) NOT NULL,
  "status" varchar(20)
);

CREATE TABLE "acoes" (
  "id" SERIAL PRIMARY KEY,
  "titulo" varchar(120) NOT NULL,
  "descricao" varchar(300) NOT NULL,
  "url_imagem" varchar(255) NOT NULL,
  "type" varchar(255) NOT NULL,
  "id_autor" integer,
  "data_criacao" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "inscricoes" (
  "id" SERIAL PRIMARY KEY,
  "id_voluntario" integer,
  "id_acao" integer,
  "data_inscricao" timestamp DEFAULT (current_timestamp)
);

ALTER TABLE "inscricoes" ADD FOREIGN KEY ("id_voluntario") REFERENCES "voluntarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "acoes" ADD FOREIGN KEY ("id_autor") REFERENCES "voluntarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inscricoes" ADD FOREIGN KEY ("id_acao") REFERENCES "acoes" ("id") DEFERRABLE INITIALLY IMMEDIATE;
